NICKNAME        = "OmegleIRC2"
REALNAME        = "OmegleIRC 2 - bigger, better, awesomer!"
IDENT           = "OmegleIRC2"
NICKSERV_PASS   = None
SERVER          = "obnauticus.com"
PORT            = 6667
CHANNELS        = [ "#omegle" ]
PREFIX_CMD      = "."
PREFIX_INVIS    = ","
MAX_CLIENTS     = 5
OMEGLE_SERVERS  = [ "cardassia.omegle.com", "bajor.omegle.com", "promenade.omegle.com" ]
